# These are default values for a local environment and should be changed for a cloud deployment
source_cluster:
  endpoint: "https://capture-proxy:9200"
  allow_insecure: true
  version: "ES_7.10"
  basic_auth:
    username: "admin"
    password: "admin"
target_cluster:
  endpoint: "https://opensearchtarget:9200"
  allow_insecure: true
  basic_auth:
    username: "admin"
    password: "myStrongPassword123!"
metrics_source:
  prometheus:
    endpoint: "http://prometheus:9090"
backfill:
  reindex_from_snapshot:
    docker:
replay:
  docker:
snapshot:
  snapshot_name: "snapshot_2023_01_01"
  snapshot_repo_name: "migration_assistant_repo"
  fs:
    repo_path: "/snapshot/test-console"
  otel_endpoint: "http://otel-collector:4317"
metadata_migration:
  from_snapshot:
  cluster_awareness_attributes: 0
  otel_endpoint: "http://otel-collector:4317"
kafka:
  broker_endpoints: "kafka:9092"
  standard: ""