version: '3.7'
services:
  webserver:
    image: 'migrations/nginx-perf-test-webserver:latest'
    networks:
      - testing
    ports:
      - "8080:80"

  captureproxy:
    image: 'migrations/capture_proxy:latest'
    networks:
      - testing
    ports:
      - "9201:9201"
    command: /runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.CaptureProxy --destinationUri  http://webserver:80 --listenPort 9201 --noCapture --destinationConnectionPoolSize 0 --numThreads 1 
    depends_on:
      - webserver

  jmeter:
    image: 'migrations/jmeter:latest'
    networks:
      - testing
    command: /bin/sh -c "/runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.JMeterLoadTest -p 9201 -s captureproxy -r HTTP; tail -f /dev/null"
    depends_on:
      - captureproxy



networks:
  testing:
    driver: bridge