version: '3'
services:
  datastash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.4
    container_name: datastash
    environment:
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - type: bind
        source: ./logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf # Overrides the default conf in the Docker image
