apiVersion: v2
name: shared-configs
description: A utility Helm chart to hold the configmaps for the common settings between all applications and the migration console.
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: helm-common
    repository: file://../helmCommon
    version: 0.1.0
