version: '3.7'
services:

  elasticsearchsource:
    image: 'migrations/elasticsearch_rfs_source:latest'
    networks:
      - migrations
    environment:
      - discovery.type=single-node
      - path.repo=/snapshots
      - AWS_ACCESS_KEY_ID=${access_key}
      - AWS_SECRET_ACCESS_KEY=${secret_key}
      - AWS_SESSION_TOKEN=${session_token}
    ports:
      - '19200:9200'
    volumes:
      - snapshotStorage:/snapshots

  # Sample command to kick off RFS here: https://github.com/opensearch-project/opensearch-migrations/blob/main/RFS/README.md#using-docker
  reindex-from-snapshot:
    image: 'migrations/reindex_from_snapshot:latest'
    depends_on:
      elasticsearchsource:
        condition: service_started
      opensearchtarget:
        condition: service_started
    networks:
      - migrations
    environment:
      - AWS_ACCESS_KEY_ID=${access_key}
      - AWS_SECRET_ACCESS_KEY=${secret_key}
      - AWS_SESSION_TOKEN=${session_token}
    volumes:
      - snapshotStorage:/snapshots

  opensearchtarget:
    image: 'opensearchproject/opensearch:2.11.1'
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    networks:
      - migrations
    ports:
      - "29200:9200"

networks:
  migrations:
    driver: bridge

volumes:
  snapshotStorage:
    driver: local