version: '3.7'
services:

  elasticsearchsource:
    image: 'migrations/empty_elasticsearch_source_5_6:latest'
    platform: linux/amd64
    networks:
      - migrations
    environment:
      - path.repo=/snapshots
      - AWS_ACCESS_KEY_ID=${access_key}
      - AWS_SECRET_ACCESS_KEY=${secret_key}
      - AWS_SESSION_TOKEN=${session_token}
    ports:
      - '19200:9200'
    volumes:
      - ./snapshots:/snapshots

  reindex-from-snapshot:
    image: 'migrations/reindex_from_snapshot:latest'
    depends_on:
      elasticsearchsource:
        condition: service_started
      opensearchtarget:
        condition: service_started
    networks:
      - migrations
    environment:
      - AWS_ACCESS_KEY_ID=${access_key}
      - AWS_SECRET_ACCESS_KEY=${secret_key}
      - AWS_SESSION_TOKEN=${session_token}
    volumes:
      - ./snapshots:/snapshots

  opensearchtarget:
    image: 'opensearchproject/opensearch:2.11.1'
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    networks:
      - migrations
    ports:
      - "29200:9200"

networks:
  migrations:
    driver: bridge
