apiVersion: v2
name: test-clusters
version: 0.1.0
dependencies:
  - name: elasticsearch
    alias: source
    condition: conditionalPackageInstalls.source
    version: "8.5.1"
    repository: https://helm.elastic.co
  - name: opensearch
    alias: target
    condition: conditionalPackageInstalls.target
    version: "2.32.0"
    repository: "https://opensearch-project.github.io/helm-charts/"
