serviceAccountName: "build-images-service-account"
namespace: "ma"
registryEndpoint: "docker-registry:5000"
repositoryUrl: "https://github.com/opensearch-project/opensearch-migrations.git"
repositoryBranch: "main"
buildImagesBaseImage: "amazoncorretto:17-al2023"
awsEKSEnabled: false
multiArchNative: false
deployBuildkitPods: false
keepJobAlive: false
localRepoMount: false
skipBuildJob: false
