{{- range (list
  (dict "kind" "CapturedTraffic"   "plural" "capturedtraffics"   "singular" "capturedtraffic")
  (dict "kind" "DataSnapshot"      "plural" "datasnapshots"      "singular" "datasnapshot")
  (dict "kind" "SnapshotMigration" "plural" "snapshotmigrations" "singular" "snapshotmigration")
) }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .plural }}.migration.opensearch.org
spec:
  group: migration.opensearch.org
  names:
    kind: {{ .kind }}
    plural: {{ .plural }}
    singular: {{ .singular }}
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
{{- end }}
