name: Gradle Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Gradle Build
        run: ./gradlew build
        working-directory: TrafficCapture

      - name: Run Tests with Coverage
        run: ./gradlew test jacocoTestReport
        working-directory: TrafficCapture

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: TrafficCapture/captureKafkaOffloader/build/reports/jacoco/test/jacocoTestReport.xml,
            TrafficCapture/captureOffloader/build/reports/jacoco/test/jacocoTestReport.xml,
            TrafficCapture/KafkaPrinter/build/reports/jacoco/test/jacocoTestReport.xml,
            TrafficCapture/nettyWireLogging/build/reports/jacoco/test/jacocoTestReport.xml,
            TrafficCapture/trafficCaptureProxyServer/build/reports/jacoco/test/jacocoTestReport.xml,
            TrafficCapture/trafficReplayer/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          fail_ci_if_error: false
